# Generated by Django 4.0.2 on 2022-03-24 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('jid', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('job_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('design', models.ImageField(blank=True, null=True, upload_to='designs/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('unit_cost', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('comitted_date', models.DateField()),
                ('discount', models.IntegerField(default=0)),
                ('isCompleted', models.BooleanField(default=False)),
                ('isDelivered', models.BooleanField(default=False)),
                ('isEmailing', models.BooleanField(default=False)),
                ('isOnHold', models.BooleanField(default=False)),
                ('mode', models.CharField(default='normal_mode', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('tax', models.FloatField(default=0.0)),
                ('delivery_date', models.DateField()),
                ('billing_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('payment_id', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chhapai.jobs')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chhapai.orders')),
            ],
        ),
        migrations.CreateModel(
            name='MidOrder',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('expected_datetime', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('isDone', models.BooleanField(default=False)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chhapai.jobs')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chhapai.orders')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chhapai.stages')),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chhapai.orders'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='order_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chhapai.ordertype'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='overseer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Challans',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chhapai.jobs')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chhapai.orders')),
            ],
        ),
    ]
