# Generated by Django 4.0.2 on 2022-02-24 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('jid', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('job_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField()),
                ('unit_cost', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('comitted_date', models.CharField(max_length=100)),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('order_type', models.CharField(max_length=200)),
                ('tax', models.FloatField()),
                ('design', models.ImageField(blank=True, null=True, upload_to='designs/')),
                ('delivery_date', models.DateField()),
                ('isEmailing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MidOrder',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('expected_datetime', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('assigned_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chhapai.jobs')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chhapai.orders')),
                ('stage', models.ManyToManyField(to='chhapai.Stages')),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chhapai.orders'),
        ),
    ]
