# Generated by Django 4.0.2 on 2022-02-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='midorder',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='midorder',
            name='stage',
        ),
        migrations.AddField(
            model_name='midorder',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chhapai.stages'),
            preserve_default=False,
        ),
    ]
