# Generated by Django 4.0.2 on 2022-03-25 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chhapai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midorder',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Stages',
        ),
    ]
