# Generated by Django 4.0.2 on 2022-02-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0002_midorder_isdone_remove_midorder_stage_midorder_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='isDelivered',
            field=models.BooleanField(default=False),
        ),
    ]
