# Generated by Django 4.0.2 on 2022-02-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0003_orders_isdelivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
    ]
