# Generated by Django 4.0.2 on 2022-04-02 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chhapai', '0003_challans_date_time_challans_dispatch_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='generated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
