# Generated by Django 4.0.2 on 2022-04-02 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chhapai', '0004_payments_generated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='challans',
            name='generated_by',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payments',
            name='created_by',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payments',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
