# Generated by Django 4.0.2 on 2022-02-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0004_alter_orders_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_date',
            field=models.CharField(max_length=100),
        ),
    ]
