# Generated by Django 4.0.2 on 2022-02-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0005_alter_orders_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
