# Generated by Django 4.0.2 on 2022-04-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0005_remove_payments_generated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challans',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chhapai.orders'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chhapai.orders'),
        ),
    ]
