# Generated by Django 4.0.2 on 2022-02-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0006_alter_jobs_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
