# Generated by Django 4.0.2 on 2022-02-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0007_alter_midorder_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midorder',
            old_name='jobs',
            new_name='job',
        ),
    ]
