# Generated by Django 4.0.2 on 2022-04-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0007_remove_jobs_iscompleted_jobs_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='dispatched_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
