# Generated by Django 4.0.2 on 2022-04-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0008_jobs_dispatched_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='challans',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
