# Generated by Django 4.0.2 on 2022-02-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0008_rename_jobs_midorder_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midorder',
            old_name='orders',
            new_name='order',
        ),
    ]
