# Generated by Django 4.0.2 on 2022-04-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0010_groupextension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midorder',
            old_name='expected_datetime',
            new_name='expected_complete_datetime',
        ),
        migrations.AddField(
            model_name='midorder',
            name='expected_start_datetime',
            field=models.DateTimeField(default='2022-02-01'),
            preserve_default=False,
        ),
    ]
