# Generated by Django 4.0.2 on 2022-03-04 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chhapai', '0010_alter_midorder_assigned_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='overseer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
