# Generated by Django 4.0.2 on 2022-05-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0011_rename_expected_datetime_midorder_expected_complete_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupextension',
            name='quality_checks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
