# Generated by Django 4.0.2 on 2022-03-04 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chhapai', '0011_jobs_overseer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='overseer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
