# Generated by Django 4.0.2 on 2022-03-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0012_alter_jobs_overseer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
