# Generated by Django 4.0.2 on 2022-06-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0013_groupextension_vendor_orders_vendor_ordertype_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
