# Generated by Django 4.0.2 on 2022-03-06 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0013_jobs_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='mode',
            field=models.CharField(default='normal_mode', max_length=100),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('payment_id', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chhapai.jobs')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chhapai.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Challans',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chhapai.jobs')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chhapai.orders')),
            ],
        ),
    ]
