# Generated by Django 4.0.2 on 2022-03-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0014_jobs_mode_payments_challans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='comitted_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='midorder',
            name='expected_datetime',
            field=models.DateTimeField(),
        ),
    ]
