# Generated by Django 4.0.2 on 2022-03-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0015_alter_jobs_comitted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_date',
            field=models.DateField(),
        ),
    ]
