# Generated by Django 4.0.2 on 2022-03-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0016_alter_orders_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='isDelivered',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='isEmailing',
        ),
        migrations.AddField(
            model_name='jobs',
            name='isDelivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobs',
            name='isEmailing',
            field=models.BooleanField(default=False),
        ),
    ]
