# Generated by Django 4.0.2 on 2022-03-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0017_remove_orders_isdelivered_remove_orders_isemailing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='isOnHold',
            field=models.BooleanField(default=False),
        ),
    ]
