# Generated by Django 4.0.2 on 2022-03-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0018_jobs_isonhold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
