# Generated by Django 4.0.2 on 2022-03-16 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chhapai', '0020_orders_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chhapai.orders'),
        ),
    ]
