# Generated by Django 4.0.2 on 2022-05-23 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_user_active_user_staff_user_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='vendor',
            field=models.BooleanField(default=False),
        ),
    ]
